version: '3.8'

services:
  spacy-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - spacy-network

networks:
  spacy-network:
    driver: bridge