name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Trigger build saat ada perubahan di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub sudah menyediakan GITHUB_TOKEN untuk login ke GHCR
          registry: ghcr.io # Pastikan registry-nya menggunakan ghcr.io untuk GitHub Container Registry

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/light-embedding:latest # Pastikan nama image dan tag sesuai
          cache-from: type=gha
          cache-to: type=gha,mode=max
